/**
 * Complete homepage CMS seed — all text, images, and repeatable items.
 * Images use /uploads/cms/home/* (copied by seedHomeMedia).
 */
import { CMS_HOME as M } from './mediaPaths.js';
import { DEFAULT_EXPLORE_LINKS, DEFAULT_PAYMENT_METHODS } from './cmsHomeConstants.js';

export function buildFullHomeSeedContent() {
  return {
    sections: {
      hero: {
        visible: true,
        autoplayMs: 6000,
        credibility: [
          { value: '10+ yrs', label: 'Serving Sylhet travelers' },
          { value: '15+', label: 'International destinations' },
          { value: '1,000+', label: 'Tickets & packages booked' },
          { value: '2–4 hrs', label: 'Typical WhatsApp response' },
        ],
        slides: [
          {
            id: 1,
            sortOrder: 0,
            visible: true,
            eyebrow: 'Kanaighat, Sylhet · Bangladesh travel desk',
            title: 'International flights, visas & packages — booked from Sylhet',
            subtitle:
              'Show Terra Flight is a full-service travel desk in Kanaighat. Clear BDT pricing, WhatsApp support, and a team you can visit in person.',
            primaryCtaText: 'Book Your Ticket',
            primaryCtaLink: '/booking',
            secondaryCtaText: 'Explore Packages',
            secondaryCtaLink: '#packages',
            image: M.hero,
            mobileImage: '',
            overlayOpacity: 0.55,
            textAlign: 'left',
            badge: 'Trusted since 2014',
            trustPoints: [
              'Physical desk at Gasbari Bazar — not an anonymous website',
              'Gulf, Southeast Asia, UK & Canada routes',
            ],
          },
          {
            id: 2,
            sortOrder: 1,
            visible: true,
            eyebrow: 'Umrah & spiritual travel',
            title: 'Umrah packages with flights, visa & Makkah hotels',
            subtitle:
              'Group and private Umrah from Dhaka and Sylhet — visa filing, ground transport, and coordinator support on departure day.',
            primaryCtaText: 'Plan Umrah',
            primaryCtaLink: '/booking',
            secondaryCtaText: 'Talk on WhatsApp',
            secondaryCtaLink: 'whatsapp',
            image: M.umrah,
            mobileImage: '',
            overlayOpacity: 0.58,
            textAlign: 'left',
            badge: 'Ramadan departures open',
            trustPoints: ['Makkah & Madinah hotel partners', 'Document-checked visa files'],
          },
          {
            id: 3,
            sortOrder: 2,
            visible: true,
            eyebrow: 'Holiday packages',
            title: 'Dubai, Thailand & Malaysia — flights, hotel & pickup',
            subtitle:
              'Fixed BDT package prices for families. Custom dates and room upgrades available on request from our Sylhet office.',
            primaryCtaText: 'Get a Quote',
            primaryCtaLink: '/contact',
            secondaryCtaText: 'View Packages',
            secondaryCtaLink: '#packages',
            image: M.dubai,
            mobileImage: '',
            overlayOpacity: 0.52,
            textAlign: 'left',
            badge: 'Best value packages',
            trustPoints: ['Airport pickup included', 'Pay via bank, bKash, Nagad or cash'],
          },
        ],
      },
      promo: {
        visible: true,
        eyebrow: 'Current offers',
        title: 'Seasonal deals for Bangladesh travelers',
        subtitle: 'Umrah groups, UAE visas, and family holiday packages with clear BDT pricing.',
        slides: [
          {
            id: 1,
            visible: true,
            sortOrder: 0,
            tag: 'Umrah season',
            title: 'Umrah packages — Dhaka & Sylhet departures',
            subtitle: 'Flights, visa, Makkah & Madinah hotels, and airport transfers.',
            cta: 'Explore Packages',
            href: '#packages',
            image: M.umrah,
            accent: 'from-emerald-700/92 to-teal-900/92',
          },
          {
            id: 2,
            visible: true,
            sortOrder: 1,
            tag: 'Visa desk',
            title: 'UAE & Malaysia visa filing from Sylhet',
            subtitle: 'Walk in with your passport and bank statements — we check everything before submission.',
            cta: 'Plan Your Trip',
            href: '/contact',
            image: M.office,
            accent: 'from-brand-800/92 to-brand-950/92',
          },
          {
            id: 3,
            visible: true,
            sortOrder: 2,
            tag: 'Holiday packages',
            title: 'Dubai & Thailand — flights, hotel & pickup included',
            subtitle: 'Fixed BDT package prices for families.',
            cta: 'Explore Packages',
            href: '#packages',
            image: M.dubai,
            accent: 'from-amber-700/90 to-orange-900/92',
          },
          {
            id: 4,
            visible: true,
            sortOrder: 3,
            tag: 'Air fares',
            title: 'Jeddah, Dubai, London & Toronto — compare fares today',
            subtitle: 'Multiple airlines quoted on WhatsApp. PNR held before you pay.',
            cta: 'Book Your Ticket',
            href: '/booking',
            image: M.sky,
            accent: 'from-sky-800/92 to-brand-950/92',
          },
        ],
      },
      services: {
        visible: true,
        eyebrow: 'What we do',
        title: 'Full travel services from one Sylhet desk',
        subtitle: 'Air tickets, visas, Umrah, hotels, and tour packages — quoted in BDT with personal follow-up.',
        items: [
          { id: 'air-ticket', visible: true, sortOrder: 0, title: 'Air Ticket Booking', description: 'Economy and business class on Biman, Emirates, Saudia, AirAsia, and more — quoted in BDT with PNR before you pay.', icon: 'plane' },
          { id: 'visa', visible: true, sortOrder: 1, title: 'Visa Processing', description: 'UAE, Malaysia, Thailand, Schengen, and UK visit visas — we prepare your file, submit, and track until stamping.', icon: 'visa' },
          { id: 'tour', visible: true, sortOrder: 2, title: 'Tour Packages', description: 'Dubai, Thailand, Malaysia, and Singapore itineraries with flights, hotels, transfers, and local coordination.', icon: 'tour' },
          { id: 'hotel', visible: true, sortOrder: 3, title: 'Hotel Booking', description: 'Hotels in Makkah, Madinah, Dubai, KL, and Bangkok matched to your dates.', icon: 'hotel' },
          { id: 'umrah', visible: true, sortOrder: 4, title: 'Umrah / Hajj', description: 'Group and private Umrah with visa, flights, Makkah & Madinah hotels, transport, and coordinator on departure day.', icon: 'umrah' },
          { id: 'corporate', visible: true, sortOrder: 5, title: 'Corporate Travel', description: 'Repeat ticketing and visa support for Sylhet and Dhaka businesses.', icon: 'corporate' },
        ],
      },
      packages: {
        visible: true,
        eyebrow: 'Tour packages',
        title: 'Real offers departing from Bangladesh',
        subtitle: 'Indicative BDT pricing — final quote depends on travel dates, airline, and room type.',
        items: [
          { id: 'dubai', visible: true, sortOrder: 0, destination: 'Dubai, UAE', duration: '4 Days / 3 Nights', departFrom: 'Dhaka (DAC) or Sylhet (ZYL)', price: '৳45,000', priceLabel: 'Starting from', priceNote: 'per person · twin share', seasonNote: 'Winter departures', image: M.dubai, features: ['Return economy flights', '4★ hotel near Deira', 'Airport pickup & drop', 'Half-day Dubai city tour'], badge: 'Popular' },
          { id: 'malaysia', visible: true, sortOrder: 1, destination: 'Kuala Lumpur, Malaysia', duration: '5 Days / 4 Nights', departFrom: 'Dhaka (DAC)', price: '৳52,000', priceLabel: 'Starting from', priceNote: 'per person · twin share', seasonNote: 'Includes daily breakfast', image: M.kl, features: ['Return flights with baggage', 'KL city-centre hotel', 'Genting Highlands day trip', 'Tourist visa filing support'], badge: 'Family pick' },
          { id: 'thailand', visible: true, sortOrder: 2, destination: 'Bangkok & Pattaya', duration: '6 Days / 5 Nights', departFrom: 'Dhaka (DAC)', price: '৳48,500', priceLabel: 'Starting from', priceNote: 'per person · twin share', seasonNote: 'Beach extension available', image: M.bangkok, features: ['Return flights', 'Pattaya beachfront hotel', 'Coral island tour', 'English-speaking local guide'], badge: 'Best value' },
          { id: 'saudi', visible: true, sortOrder: 3, destination: 'Umrah — Saudi Arabia', duration: '10 Days / 9 Nights', departFrom: 'Dhaka or Sylhet', price: '৳1,25,000', priceLabel: 'Packages from', priceNote: 'per pilgrim · quad share', seasonNote: 'Ramadan slots — book early', image: M.umrah, features: ['Return flights + Umrah visa', 'Makkah hotel walking distance', 'Madinah stay included', 'Ziyarat & ground transport'], badge: 'Spiritual' },
          { id: 'singapore', visible: true, sortOrder: 4, destination: 'Singapore', duration: '4 Days / 3 Nights', departFrom: 'Dhaka (DAC)', price: '৳58,000', priceLabel: 'Starting from', priceNote: 'per person · twin share', seasonNote: 'School-holiday dates fill quickly', image: M.singapore, features: ['Return flights', 'Bugis / Marina hotel', 'Sentosa day pass', 'EZ-Link metro card'], badge: 'Trending' },
          { id: 'turkey', visible: true, sortOrder: 5, destination: 'Istanbul, Turkey', duration: '7 Days / 6 Nights', departFrom: 'Dhaka via connecting hub', price: '৳89,000', priceLabel: 'Starting from', priceNote: 'per person · twin share', seasonNote: 'Visa appointment assistance included', image: M.istanbul, features: ['Return flights', 'Sultanahmet boutique hotel', 'Bosphorus dinner cruise', 'Old city guided walk'], badge: 'Premium' },
        ],
      },
      worldMap: {
        visible: true,
        eyebrow: 'Bangladesh to the world',
        title: 'Routes we book every week',
        subtitle: 'From Sylhet and Dhaka to the Gulf, Southeast Asia, Europe, and North America.',
        destinations: [
          { id: 'sa', label: 'Saudi Arabia', short: 'Saudi', x: 42, y: 38 },
          { id: 'uae', label: 'UAE', short: 'UAE', x: 48, y: 42 },
          { id: 'my', label: 'Malaysia', short: 'MY', x: 72, y: 52 },
          { id: 'sg', label: 'Singapore', short: 'SG', x: 74, y: 54 },
          { id: 'th', label: 'Thailand', short: 'TH', x: 70, y: 48 },
          { id: 'tr', label: 'Turkey', short: 'TR', x: 38, y: 32 },
          { id: 'uk', label: 'UK', short: 'UK', x: 28, y: 28 },
          { id: 'ca', label: 'Canada', short: 'CA', x: 18, y: 22 },
        ],
        stats: [
          { value: 15, suffix: '+', label: 'Countries we book to' },
          { value: 500, suffix: '+', label: 'Clients served each year' },
          { value: 24, suffix: '/7', label: 'WhatsApp enquiry line' },
          { value: 100, suffix: '%', label: 'Visa files document-checked' },
        ],
      },
      about: {
        visible: true,
        eyebrow: 'About us',
        title: 'A Sylhet travel agency with nationwide reach',
        lead: 'Full-service travel desk at Gasbari Bazar, Kanaighat — transparent BDT pricing and consultants you can speak to directly.',
        body: 'From a last-minute Jeddah ticket to a Malaysia family package or corporate travel for your business, we stay with you from the first quote to boarding pass delivery.',
        image: M.office,
        imageCaption: 'Your local international travel desk',
        imageLocation: 'Kanaighat, Sylhet',
      },
      testimonials: {
        visible: true,
        eyebrow: 'Client stories',
        title: 'Trusted by travelers across Sylhet & Dhaka',
        subtitle: 'Real feedback from families, business travelers, and Umrah groups we have served.',
        items: [
          { id: 1, visible: true, sortOrder: 0, name: 'Rahim Uddin', role: 'Shop owner', location: 'Ambarkhana, Sylhet', trip: 'Dubai family tickets (4 pax)', rating: 5, text: 'Show Terra Flight gave the clearest BDT breakdown on WhatsApp and issued all four PNRs the same afternoon.', avatar: M.team1 },
          { id: 2, visible: true, sortOrder: 1, name: 'Fatima Begum', role: 'Homemaker', location: 'Kanaighat, Sylhet', trip: 'Umrah package · Feb 2025', rating: 5, text: 'Our group of 22 left from Dhaka with everything arranged — flights, visa, Makkah hotel, and Madinah stay.', avatar: M.team2 },
          { id: 3, visible: true, sortOrder: 2, name: 'Karim Ahmed', role: 'Import business', location: 'Gulshan, Dhaka', trip: 'Malaysia business visa', rating: 5, text: 'Visa approved in nine working days. They now handle our company recurring ticket bookings too.', avatar: M.team3 },
          { id: 4, visible: true, sortOrder: 3, name: 'Nusrat Jahan', role: 'School teacher', location: 'Zindabazar, Sylhet', trip: 'Bangkok & Pattaya package', rating: 5, text: 'First international holiday for our family of five. Pickup was waiting at BKK airport with our name board.', avatar: M.team4 },
        ],
      },
      gallery: {
        visible: true,
        eyebrow: 'Our work',
        title: 'Moments from departures & visa wins',
        subtitle: 'Airport send-offs, Umrah groups, and visa pickups at our Kanaighat office.',
        filters: [
          { id: 'all', label: 'All moments' },
          { id: 'tours', label: 'Holiday tours' },
          { id: 'visa', label: 'Visa success' },
          { id: 'airport', label: 'Airport send-offs' },
          { id: 'group', label: 'Group departures' },
        ],
        items: [
          { id: 1, visible: true, sortOrder: 0, category: 'tours', title: 'Dubai Eid group · 18 travelers', subtitle: 'Departure lounge, HSIA · Apr 2025', image: M.galleryDubai },
          { id: 2, visible: true, sortOrder: 1, category: 'visa', title: 'UAE visa stamped — client pickup', subtitle: 'Kanaighat office · visa desk', image: M.office },
          { id: 3, visible: true, sortOrder: 2, category: 'airport', title: 'Sylhet families seeing off to Jeddah', subtitle: 'Osmani International · Umrah season', image: M.galleryAirport },
          { id: 4, visible: true, sortOrder: 3, category: 'group', title: 'Umrah group at Masjid an-Nabawi', subtitle: '22 pilgrims · guided ziyarat', image: M.umrah },
          { id: 5, visible: true, sortOrder: 4, category: 'tours', title: 'Bangkok temple & river tour', subtitle: 'Thailand package · family of 5', image: M.bangkok },
          { id: 6, visible: true, sortOrder: 5, category: 'airport', title: 'Ticket handover before UK departure', subtitle: 'Show Terra Flight desk', image: M.galleryAirport },
          { id: 7, visible: true, sortOrder: 6, category: 'group', title: 'Corporate retreat — Kuala Lumpur', subtitle: '12 staff · Genting extension', image: M.kl },
          { id: 8, visible: true, sortOrder: 7, category: 'visa', title: 'Schengen file review session', subtitle: 'Document checklist · walk-in support', image: M.office },
        ],
      },
      team: {
        visible: true,
        eyebrow: 'Meet the team',
        title: 'Consultants you can call or visit',
        subtitle: 'Walk in at Gasbari Bazar or message us on WhatsApp — the same team handles your booking.',
        items: [
          { id: 1, visible: true, sortOrder: 0, name: 'Kamil Hussen', role: 'Managing Director', bio: 'Founded the Kanaighat desk in 2014. Negotiates airline allotments for Gulf and UK routes.', image: M.team1 },
          { id: 2, visible: true, sortOrder: 1, name: 'Ayesha Rahman', role: 'Visa & Documentation Officer', bio: 'Prepares UAE, Malaysia, Thailand, and Schengen files before embassy submission.', image: M.team2 },
          { id: 3, visible: true, sortOrder: 2, name: 'Tanvir Hasan', role: 'Umrah & Tour Coordinator', bio: 'Builds group Umrah and holiday itineraries with hotel partners in Makkah, Madinah, Dubai, and Bangkok.', image: M.team3 },
          { id: 4, visible: true, sortOrder: 3, name: 'Sadia Akter', role: 'Customer Care · WhatsApp Desk', bio: 'First point of contact for quotes, PNR delivery, date changes, and refund follow-ups.', image: M.team4 },
        ],
      },
      trust: {
        visible: true,
        eyebrow: 'Why book with us',
        title: 'A Sylhet travel desk you can visit in person',
        subtitle: '',
        items: [
          { title: 'Sylhet consultants you can meet', desc: 'Visit our Gasbari Bazar desk, call, or message WhatsApp.' },
          { title: 'Clear BDT quotes upfront', desc: 'Total fare confirmed before payment. No last-minute add-ons.' },
          { title: 'One desk for the full journey', desc: 'Air tickets, visa filing, Umrah groups, hotels, and corporate accounts.' },
          { title: 'Bank, bKash, Nagad & cash', desc: 'Pay the way you already send money at home.' },
        ],
        assurances: ['GDS & airline-direct fares', 'Document-checked visa files', 'PNR delivery before payment'],
        payments: [
          { id: 'bank', label: 'Bank Transfer', sub: 'Any Bangladeshi bank · office receipt issued', color: 'bg-blue-700' },
          { id: 'bkash', label: 'bKash', sub: 'Personal & merchant payment', color: 'bg-[#e2136e]' },
          { id: 'nagad', label: 'Nagad', sub: 'Personal & merchant payment', color: 'bg-[#f69220]' },
        ],
        stats: [
          { value: '10+', label: 'Years in Sylhet' },
          { value: '1,000+', label: 'Bookings handled' },
          { value: '4.9★', label: 'Client rating' },
        ],
      },
      paymentStrip: { visible: true, label: 'Pay via', supportSubline: 'Booking help 7 days a week', methods: DEFAULT_PAYMENT_METHODS },
      cta: {
        visible: true,
        eyebrow: 'Start your booking',
        title: 'Ready to book your next trip from Bangladesh?',
        subtitle: 'Get a fare quote, visa guidance, or package price — our Kanaighat team responds quickly on WhatsApp and phone.',
        primaryCtaText: 'Talk on WhatsApp',
        primaryCtaLink: 'whatsapp',
        secondaryCtaText: 'Call Now',
        secondaryCtaLink: 'tel',
        tertiaryCtaText: 'Plan Your Trip',
        tertiaryCtaLink: '/booking',
        image: M.sky,
      },
      contact: {
        visible: true,
        eyebrow: 'Contact',
        title: 'Visit us or message on WhatsApp',
        subtitle: 'Gasbari Bazar, Ground Floor of BRAC Bank, Kanaighat, Sylhet-3183',
        officeTitle: 'Office',
        officeHeading: 'Kanaighat, Sylhet',
        directLineTitle: 'Direct line',
        directLineHeading: 'Phone & email',
        nextStepTitle: 'Next step',
        nextStepHeading: 'Start your booking',
        nextStepBody: 'Tell us your route and dates — we reply with fare options and package pricing in BDT.',
        whatsappButtonText: 'Message on WhatsApp',
      },
      footer: {
        visible: true,
        tagline: 'International air tickets, visa processing, Umrah packages, and holiday tours from our Kanaighat, Sylhet office.',
        supportNote: 'WhatsApp replies typically within 2–4 hours on business days',
        ctaText: 'Book Your Ticket',
        ctaLink: '/booking',
        exploreTitle: 'Explore',
        servicesTitle: 'Services',
        contactTitle: 'Contact',
        copyrightText: 'All rights reserved.',
        legalText: '',
        locationLine: 'Gasbari Bazar, Kanaighat, Sylhet, Bangladesh',
        exploreLinks: DEFAULT_EXPLORE_LINKS,
        paymentMethods: DEFAULT_PAYMENT_METHODS,
        showPaymentStrip: true,
      },
    },
    supportReassurance: {
      response: 'WhatsApp replies typically within 2–4 hours on business days',
      hours: 'Office Sun–Thu 9:00am–8:00pm · Sat 10:00am–6:00pm',
      booking: 'We confirm seat availability and total BDT price before you pay',
    },
  };
}

export default buildFullHomeSeedContent;
